# Generated by Django 4.2 on 2025-06-16 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventDetails',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=50, unique=True)),
                ('eventDescription', models.CharField(max_length=100)),
                ('eventDate', models.DateTimeField()),
                ('venue', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('mobile', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='membershipDetails',
            fields=[
                ('membershipCategory', models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=20)),
                ('membershipId', models.AutoField(primary_key=True, serialize=False)),
                ('validity', models.DateField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mallusers.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='eventRegister',
            fields=[
                ('registraionId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mallusers.userdetails')),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mallusers.eventdetails')),
            ],
        ),
    ]
